theme: jekyll-theme-minimal
title: Welcome to benjaminsmyers’ homepage!
description: Feel free to to bookmark this to keep an eye out for upcoming projects. I'm always happy to meet new people and I welcome new connections, so don't hesitate to send me a message! 
